### ISSUE TITLE
sql语句应该修改

### ISSUE THREAD

**Issue by xianxueniao150** [tomoya92/activiti-demo#2]
INSERT INTO `activiti-demo`.`user(`id`, `password`, `rank`, `username`, `leader_id`, `in_time`)
VALUES
	(1, '123123', '管理员', 'admin', NULL, '2019-04-22 14:19:23'),
	(3, '123123', '总经理', 'user1', NULL, '2019-04-22 14:19:23'),
        (2, '123123', '部门经理', 'user2', 3, '2019-04-22 14:19:23'),
	(5, '123123', '员工', 'user3', 2, '2019-04-22 14:21:38'),
	(6, '123123', '员工', 'user4', 2, '2019-04-22 14:22:56');

**Comment by atjiu** [comment]
为啥？
